export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATION_START = 'FETCH_LOCATION_START';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAIL = 'FETCH_LOCATION_FAIL';


export const CLEAR_LOCATION = 'CLEAR_LOCATION';
export const CLEAR_LOCATION_START = 'CLEAR_LOCATION_START';
export const CLEAR_LOCATION_SUCCESS = 'CLEAR_LOCATION_SUCCESS';
export const CLEAR_LOCATION_FAIL = 'CLEAR_LOCATION_FAIL';

export const FETCH_WEATHER_BY_LOCATION = 'FETCH_WEATHER_BY_LOCATION';
export const FETCH_WEATHER_BY_LOCATION_START = 'FETCH_WEATHER_BY_LOCATION_START';
export const FETCH_WEATHER_BY_LOCATION_SUCCESS = 'FETCH_WEATHER_BY_LOCATION_SUCCESS';
export const FETCH_WEATHER_BY_LOCATION_FAIL = 'FETCH_WEATHER_BY_LOCATION_FAIL';

export const INIT_INFO = 'INIT_INFO';
